---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version: "2"

linters:
  disable-all: true
  disable:
    - errcheck
    - staticcheck
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - cyclop
    - depguard
    - dogsled
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    # - funlen  # Some functions are long
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    # - godot
    # - goheader
    - gomoddirectives
    - goprintffuncname
    # - gosec
    - lll
    - misspell
    - mnd
    - nakedret
    - nilnil
    # - noctx
    # - nolintlint
    # - prealloc
    - predeclared
    # - revive
    # - stylecheck
    # - tagliatelle
    # - testpackage
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - whitespace
  settings:
    gomoddirectives:
      replace-local: true
    depguard:
      rules:
        main:
          files:
            - $all
            - "!$test"
          allow:
            - $gostd
            - google.golang.org/grpc
            - google.golang.org/protobuf
            - github.com/open-edge-platform
            - github.com/cenkalti/backoff/v4
            - github.com/prometheus/client_golang/prometheus
          deny: []
        test:
          files:
            - $test
          allow:
            - $gostd
            - google.golang.org/grpc
            - github.com/open-edge-platform
            - github.com/undefinedlabs/go-mpatch
            - github.com/golang/mock/gomock
            - github.com/stretchr/testify/require
            - github.com/stretchr/testify/assert
            - github.com/google/go-cmp/cmp
            - github.com/google/uuid
          deny: []
    gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      # These 3 will detect many cases, but they do sense
      # if it's performance oriented code
      - hugeParam
      - rangeExprCopy
      - rangeValCopy
      - unnamedResult

  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale: US
    ignore-words:
      - someword

  nakedret:
    # No naked returns, ever.
    max-func-lines: 1
  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake
        xml: camel
        bson: camel
        avro: snake
        mapstructure: kebab

  unparam:
    # Inspect exported functions, default is false. Set to true if no external
    # program/library imports your code. XXX: if you enable this setting, unparam
    # will report a lot of false-positives in text editors: if it's called for
    # subdir of a project it can't find external interfaces. All text editor
    # integrations with golangci-lint call it on a directory with the changed file.
    check-exported: false
    cyclop:
      max-complexity: 10
    exhaustive:
      default-signifies-exhaustive: true
    lll:
      line-length: 130
      tab-width: 4
    funlen:
      lines: 100
      statements: 50
  exclusions:
    generated: lax
    paths:
      - pkg/api/
      - third_party$
      - builtin$
      - examples$

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly
  go: ""

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  # When set to `true` linter will analyze only new code which are
  # not committed or after some specific revision. This is a cool
  # feature when you're going to introduce linter into a big project.
  # But I prefer going gradually package by package.
  # So, it's set to `false` to scan all code.
  new: false
  fix: false

  uniq-by-line: false

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
    html:
      path: out/golangci-lint_report.html
  sort-results: true

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/open-edge-platform)
  exclusions:
    generated: lax
    paths:
      - pkg/api/
      - third_party$
      - builtin$
      - examples$
