# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = [
  "VERSION",
  "go.sum",

  "**.md",
  "pkg/api/hostmgr/proto/*.pb*.go",
  "pkg/api/buf.lock",
]

SPDX-FileCopyrightText = "2025 Intel Corporation"
SPDX-License-Identifier = "Apache-2.0"
