// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: maintmgr/v1/maintmgr.proto

package maintmgrv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MaintmgrServiceClient is the client API for MaintmgrService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MaintmgrServiceClient interface {
	PlatformUpdateStatus(ctx context.Context, in *PlatformUpdateStatusRequest, opts ...grpc.CallOption) (*PlatformUpdateStatusResponse, error)
}

type maintmgrServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMaintmgrServiceClient(cc grpc.ClientConnInterface) MaintmgrServiceClient {
	return &maintmgrServiceClient{cc}
}

func (c *maintmgrServiceClient) PlatformUpdateStatus(ctx context.Context, in *PlatformUpdateStatusRequest, opts ...grpc.CallOption) (*PlatformUpdateStatusResponse, error) {
	out := new(PlatformUpdateStatusResponse)
	err := c.cc.Invoke(ctx, "/maintmgr.v1.MaintmgrService/PlatformUpdateStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MaintmgrServiceServer is the server API for MaintmgrService service.
// All implementations should embed UnimplementedMaintmgrServiceServer
// for forward compatibility
type MaintmgrServiceServer interface {
	PlatformUpdateStatus(context.Context, *PlatformUpdateStatusRequest) (*PlatformUpdateStatusResponse, error)
}

// UnimplementedMaintmgrServiceServer should be embedded to have forward compatible implementations.
type UnimplementedMaintmgrServiceServer struct {
}

func (UnimplementedMaintmgrServiceServer) PlatformUpdateStatus(context.Context, *PlatformUpdateStatusRequest) (*PlatformUpdateStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlatformUpdateStatus not implemented")
}

// UnsafeMaintmgrServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MaintmgrServiceServer will
// result in compilation errors.
type UnsafeMaintmgrServiceServer interface {
	mustEmbedUnimplementedMaintmgrServiceServer()
}

func RegisterMaintmgrServiceServer(s grpc.ServiceRegistrar, srv MaintmgrServiceServer) {
	s.RegisterService(&MaintmgrService_ServiceDesc, srv)
}

func _MaintmgrService_PlatformUpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformUpdateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MaintmgrServiceServer).PlatformUpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/maintmgr.v1.MaintmgrService/PlatformUpdateStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MaintmgrServiceServer).PlatformUpdateStatus(ctx, req.(*PlatformUpdateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MaintmgrService_ServiceDesc is the grpc.ServiceDesc for MaintmgrService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MaintmgrService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "maintmgr.v1.MaintmgrService",
	HandlerType: (*MaintmgrServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlatformUpdateStatus",
			Handler:    _MaintmgrService_PlatformUpdateStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "maintmgr/v1/maintmgr.proto",
}
