---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version: "2"

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - cyclop
    - depguard
    - dogsled
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomoddirectives
    - goprintffuncname
    - lll
    - misspell
    - mnd
    - nakedret
    - nilerr
    - nilnil
    - predeclared
    - tagliatelle
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace
  disable:
    - errcheck
    - staticcheck
    - revive
    - noctx
    - nolintlint
    - prealloc
  formatters:
    - gci
    - gofmt
    - gofumpt
  settings:
    cyclop:
      # SDL requirements dictate a maximum cyclomatic complexity of 10
      max-complexity: 10
    misspell:
      locale: US
    lll:
      line-length: 130
      tab-width: 4
    funlen:
      lines: 100
      statements: 50
    exhaustive:
      default-signifies-exhaustive: true
    gci:
      sections:
        # Standard section: captures all standard packages.
        - standard
        # Default section: contains all imports that could not be matched to another section type.
        - default
        # Custom section: groups all imports with the specified Prefix.
        - prefix(github.com/open-edge-platform)
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        # These 3 will detect many cases, but they do sense
        # if it's performance oriented code
        - hugeParam
        - rangeExprCopy
        - rangeValCopy
        - unnamedResult
    nakedret:
      # No naked returns, ever.
      max-func-lines: 1
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
          xml: camel
          bson: camel
          avro: snake
          mapstructure: kebab
    depguard:
      rules:
        main:
          files:
            - $all
            - "!$test"
          allow:
            - $gostd
            - github.com/open-edge-platform
            - entgo.io/ent
            - github.com/goccy/go-json
            - github.com/google
            - github.com/grpc-ecosystem
            - github.com/mennanov/fmutils
            - github.com/labstack/echo
            - github.com/open-policy-agent
            - github.com/pkg/errors
            - github.com/rs/zerolog
            - github.com/cenkalti/backoff
            - github.com/stretchr/testify/require
            - github.com/iancoleman/strcase
            - github.com/jackc/pgx/v5/stdlib
            - github.com/hashicorp/vault/api
            - github.com/stretchr/testify/mock
            - github.com/prometheus/client_golang/prometheus
            - google.golang.org/grpc
            - google.golang.org/protobuf
            - gopkg.in/yaml.v2
          deny: []
        test:
          files:
            - $test
          allow:
            - $gostd
            - github.com/open-edge-platform
            - github.com/goccy/go-json
            - github.com/google
            - github.com/grpc-ecosystem
            - github.com/mennanov/fmutils
            - github.com/rs/zerolog
            - github.com/stretchr/testify/require
            - github.com/stretchr/testify/assert
            - github.com/grpc-ecosystem/go-grpc-middleware/util/metautils
            - github.com/hashicorp/vault/api
            - github.com/stretchr/testify/mock
            - google.golang.org/grpc
            - google.golang.org/protobuf
            - gopkg.in/yaml.v2
          deny: []

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly
  go: ""

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
  exclude:
    - Error return value of `.*Close` is not checked
    - Error return value of `.*Flush` is not checked
    - Error return value of `.*Write` is not checked
    - Error return value of `.*Stop` is not checked

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
    html:
      path: out/golangci-lint.html
    junit-xml:
      path: out/golangci-lint.xml
  uniq-by-line: false
  sort-results: true
