// SPDX-FileCopyrightText: (C) 2025 Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: remaccessmgr/v1/remacessmgr.proto

package remaccessmgrv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RemaccessmgrService_GetRemoteAccessConfigByGuid_FullMethodName = "/remaccessmgr.v1.RemaccessmgrService/GetRemoteAccessConfigByGuid"
)

// RemaccessmgrServiceClient is the client API for RemaccessmgrService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RemaccessmgrServiceClient interface {
	GetRemoteAccessConfigByGuid(ctx context.Context, in *GetRemoteAccessConfigByGuidRequest, opts ...grpc.CallOption) (*GetResourceAccessConfigResponse, error)
}

type remaccessmgrServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRemaccessmgrServiceClient(cc grpc.ClientConnInterface) RemaccessmgrServiceClient {
	return &remaccessmgrServiceClient{cc}
}

func (c *remaccessmgrServiceClient) GetRemoteAccessConfigByGuid(ctx context.Context, in *GetRemoteAccessConfigByGuidRequest, opts ...grpc.CallOption) (*GetResourceAccessConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResourceAccessConfigResponse)
	err := c.cc.Invoke(ctx, RemaccessmgrService_GetRemoteAccessConfigByGuid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemaccessmgrServiceServer is the server API for RemaccessmgrService service.
// All implementations should embed UnimplementedRemaccessmgrServiceServer
// for forward compatibility.
type RemaccessmgrServiceServer interface {
	GetRemoteAccessConfigByGuid(context.Context, *GetRemoteAccessConfigByGuidRequest) (*GetResourceAccessConfigResponse, error)
}

// UnimplementedRemaccessmgrServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRemaccessmgrServiceServer struct{}

func (UnimplementedRemaccessmgrServiceServer) GetRemoteAccessConfigByGuid(context.Context, *GetRemoteAccessConfigByGuidRequest) (*GetResourceAccessConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRemoteAccessConfigByGuid not implemented")
}
func (UnimplementedRemaccessmgrServiceServer) testEmbeddedByValue() {}

// UnsafeRemaccessmgrServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemaccessmgrServiceServer will
// result in compilation errors.
type UnsafeRemaccessmgrServiceServer interface {
	mustEmbedUnimplementedRemaccessmgrServiceServer()
}

func RegisterRemaccessmgrServiceServer(s grpc.ServiceRegistrar, srv RemaccessmgrServiceServer) {
	// If the following call pancis, it indicates UnimplementedRemaccessmgrServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RemaccessmgrService_ServiceDesc, srv)
}

func _RemaccessmgrService_GetRemoteAccessConfigByGuid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRemoteAccessConfigByGuidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemaccessmgrServiceServer).GetRemoteAccessConfigByGuid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemaccessmgrService_GetRemoteAccessConfigByGuid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemaccessmgrServiceServer).GetRemoteAccessConfigByGuid(ctx, req.(*GetRemoteAccessConfigByGuidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RemaccessmgrService_ServiceDesc is the grpc.ServiceDesc for RemaccessmgrService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemaccessmgrService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remaccessmgr.v1.RemaccessmgrService",
	HandlerType: (*RemaccessmgrServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRemoteAccessConfigByGuid",
			Handler:    _RemaccessmgrService_GetRemoteAccessConfigByGuid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "remaccessmgr/v1/remacessmgr.proto",
}
