// SPDX-FileCopyrightText: (C) 2025 Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: remaccessmgr/v1/remacessmgr.proto

package remaccessmgrv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigStatus int32

const (
	ConfigStatus_CONFIG_STATUS_UNSPECIFIED ConfigStatus = 0
	ConfigStatus_CONFIG_STATUS_NONE        ConfigStatus = 1
	ConfigStatus_CONFIG_STATUS_PENDING     ConfigStatus = 2
	ConfigStatus_CONFIG_STATUS_ACTIVE      ConfigStatus = 3
	ConfigStatus_CONFIG_STATUS_DISABLED    ConfigStatus = 4
	ConfigStatus_CONFIG_STATUS_ERROR       ConfigStatus = 5
)

// Enum value maps for ConfigStatus.
var (
	ConfigStatus_name = map[int32]string{
		0: "CONFIG_STATUS_UNSPECIFIED",
		1: "CONFIG_STATUS_NONE",
		2: "CONFIG_STATUS_PENDING",
		3: "CONFIG_STATUS_ACTIVE",
		4: "CONFIG_STATUS_DISABLED",
		5: "CONFIG_STATUS_ERROR",
	}
	ConfigStatus_value = map[string]int32{
		"CONFIG_STATUS_UNSPECIFIED": 0,
		"CONFIG_STATUS_NONE":        1,
		"CONFIG_STATUS_PENDING":     2,
		"CONFIG_STATUS_ACTIVE":      3,
		"CONFIG_STATUS_DISABLED":    4,
		"CONFIG_STATUS_ERROR":       5,
	}
)

func (x ConfigStatus) Enum() *ConfigStatus {
	p := new(ConfigStatus)
	*p = x
	return p
}

func (x ConfigStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_remaccessmgr_v1_remacessmgr_proto_enumTypes[0].Descriptor()
}

func (ConfigStatus) Type() protoreflect.EnumType {
	return &file_remaccessmgr_v1_remacessmgr_proto_enumTypes[0]
}

func (x ConfigStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigStatus.Descriptor instead.
func (ConfigStatus) EnumDescriptor() ([]byte, []int) {
	return file_remaccessmgr_v1_remacessmgr_proto_rawDescGZIP(), []int{0}
}

type GetRemoteAccessConfigByGuidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	TenantID      string                 `protobuf:"bytes,2,opt,name=tenantID,proto3" json:"tenantID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRemoteAccessConfigByGuidRequest) Reset() {
	*x = GetRemoteAccessConfigByGuidRequest{}
	mi := &file_remaccessmgr_v1_remacessmgr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRemoteAccessConfigByGuidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRemoteAccessConfigByGuidRequest) ProtoMessage() {}

func (x *GetRemoteAccessConfigByGuidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remaccessmgr_v1_remacessmgr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRemoteAccessConfigByGuidRequest.ProtoReflect.Descriptor instead.
func (*GetRemoteAccessConfigByGuidRequest) Descriptor() ([]byte, []int) {
	return file_remaccessmgr_v1_remacessmgr_proto_rawDescGZIP(), []int{0}
}

func (x *GetRemoteAccessConfigByGuidRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetRemoteAccessConfigByGuidRequest) GetTenantID() string {
	if x != nil {
		return x.TenantID
	}
	return ""
}

type AgentRemoteAccessSpec struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	RemoteAccessProxyEndpoint string                 `protobuf:"bytes,1,opt,name=remote_access_proxy_endpoint,json=remoteAccessProxyEndpoint,proto3" json:"remote_access_proxy_endpoint,omitempty"`
	SessionToken              string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	ReverseBindPort           uint32                 `protobuf:"varint,3,opt,name=reverse_bind_port,json=reverseBindPort,proto3" json:"reverse_bind_port,omitempty"`
	TargetHost                string                 `protobuf:"bytes,4,opt,name=target_host,json=targetHost,proto3" json:"target_host,omitempty"`
	TargetPort                uint32                 `protobuf:"varint,5,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	SshUser                   string                 `protobuf:"bytes,6,opt,name=ssh_user,json=sshUser,proto3" json:"ssh_user,omitempty"`
	ExpirationTimestamp       uint64                 `protobuf:"varint,7,opt,name=expiration_timestamp,json=expirationTimestamp,proto3" json:"expiration_timestamp,omitempty"`
	Uuid                      string                 `protobuf:"bytes,8,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *AgentRemoteAccessSpec) Reset() {
	*x = AgentRemoteAccessSpec{}
	mi := &file_remaccessmgr_v1_remacessmgr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRemoteAccessSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRemoteAccessSpec) ProtoMessage() {}

func (x *AgentRemoteAccessSpec) ProtoReflect() protoreflect.Message {
	mi := &file_remaccessmgr_v1_remacessmgr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRemoteAccessSpec.ProtoReflect.Descriptor instead.
func (*AgentRemoteAccessSpec) Descriptor() ([]byte, []int) {
	return file_remaccessmgr_v1_remacessmgr_proto_rawDescGZIP(), []int{1}
}

func (x *AgentRemoteAccessSpec) GetRemoteAccessProxyEndpoint() string {
	if x != nil {
		return x.RemoteAccessProxyEndpoint
	}
	return ""
}

func (x *AgentRemoteAccessSpec) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *AgentRemoteAccessSpec) GetReverseBindPort() uint32 {
	if x != nil {
		return x.ReverseBindPort
	}
	return 0
}

func (x *AgentRemoteAccessSpec) GetTargetHost() string {
	if x != nil {
		return x.TargetHost
	}
	return ""
}

func (x *AgentRemoteAccessSpec) GetTargetPort() uint32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *AgentRemoteAccessSpec) GetSshUser() string {
	if x != nil {
		return x.SshUser
	}
	return ""
}

func (x *AgentRemoteAccessSpec) GetExpirationTimestamp() uint64 {
	if x != nil {
		return x.ExpirationTimestamp
	}
	return 0
}

func (x *AgentRemoteAccessSpec) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ConfigError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigError) Reset() {
	*x = ConfigError{}
	mi := &file_remaccessmgr_v1_remacessmgr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigError) ProtoMessage() {}

func (x *ConfigError) ProtoReflect() protoreflect.Message {
	mi := &file_remaccessmgr_v1_remacessmgr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigError.ProtoReflect.Descriptor instead.
func (*ConfigError) Descriptor() ([]byte, []int) {
	return file_remaccessmgr_v1_remacessmgr_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetResourceAccessConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Status        ConfigStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=remaccessmgr.v1.ConfigStatus" json:"status,omitempty"`
	Spec          *AgentRemoteAccessSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	Error         *ConfigError           `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceAccessConfigResponse) Reset() {
	*x = GetResourceAccessConfigResponse{}
	mi := &file_remaccessmgr_v1_remacessmgr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceAccessConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceAccessConfigResponse) ProtoMessage() {}

func (x *GetResourceAccessConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remaccessmgr_v1_remacessmgr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceAccessConfigResponse.ProtoReflect.Descriptor instead.
func (*GetResourceAccessConfigResponse) Descriptor() ([]byte, []int) {
	return file_remaccessmgr_v1_remacessmgr_proto_rawDescGZIP(), []int{3}
}

func (x *GetResourceAccessConfigResponse) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GetResourceAccessConfigResponse) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *GetResourceAccessConfigResponse) GetStatus() ConfigStatus {
	if x != nil {
		return x.Status
	}
	return ConfigStatus_CONFIG_STATUS_UNSPECIFIED
}

func (x *GetResourceAccessConfigResponse) GetSpec() *AgentRemoteAccessSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *GetResourceAccessConfigResponse) GetError() *ConfigError {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_remaccessmgr_v1_remacessmgr_proto protoreflect.FileDescriptor

const file_remaccessmgr_v1_remacessmgr_proto_rawDesc = "" +
	"\n" +
	"!remaccessmgr/v1/remacessmgr.proto\x12\x0fremaccessmgr.v1\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"l\n" +
	"\"GetRemoteAccessConfigByGuidRequest\x12\x1e\n" +
	"\x04uuid\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05($\xb0\x01\x01R\x04uuid\x12&\n" +
	"\btenantID\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05($\xb0\x01\x01R\btenantID\"\xcd\x02\n" +
	"\x15AgentRemoteAccessSpec\x12?\n" +
	"\x1cremote_access_proxy_endpoint\x18\x01 \x01(\tR\x19remoteAccessProxyEndpoint\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12*\n" +
	"\x11reverse_bind_port\x18\x03 \x01(\rR\x0freverseBindPort\x12\x1f\n" +
	"\vtarget_host\x18\x04 \x01(\tR\n" +
	"targetHost\x12\x1f\n" +
	"\vtarget_port\x18\x05 \x01(\rR\n" +
	"targetPort\x12\x19\n" +
	"\bssh_user\x18\x06 \x01(\tR\asshUser\x121\n" +
	"\x14expiration_timestamp\x18\a \x01(\x04R\x13expirationTimestamp\x12\x12\n" +
	"\x04uuid\x18\b \x01(\tR\x04uuid\"!\n" +
	"\vConfigError\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"\x97\x02\n" +
	"\x1fGetResourceAccessConfigResponse\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12;\n" +
	"\vobserved_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x125\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1d.remaccessmgr.v1.ConfigStatusR\x06status\x12:\n" +
	"\x04spec\x18\x04 \x01(\v2&.remaccessmgr.v1.AgentRemoteAccessSpecR\x04spec\x122\n" +
	"\x05error\x18\x05 \x01(\v2\x1c.remaccessmgr.v1.ConfigErrorR\x05error*\xaf\x01\n" +
	"\fConfigStatus\x12\x1d\n" +
	"\x19CONFIG_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CONFIG_STATUS_NONE\x10\x01\x12\x19\n" +
	"\x15CONFIG_STATUS_PENDING\x10\x02\x12\x18\n" +
	"\x14CONFIG_STATUS_ACTIVE\x10\x03\x12\x1a\n" +
	"\x16CONFIG_STATUS_DISABLED\x10\x04\x12\x17\n" +
	"\x13CONFIG_STATUS_ERROR\x10\x052\x9e\x01\n" +
	"\x13RemaccessmgrService\x12\x86\x01\n" +
	"\x1bGetRemoteAccessConfigByGuid\x123.remaccessmgr.v1.GetRemoteAccessConfigByGuidRequest\x1a0.remaccessmgr.v1.GetResourceAccessConfigResponse\"\x00BcZagithub.com/open-edge-platform/infra-managers/remote-access/pkg/api/remaccessmgr/v1;remaccessmgrv1b\x06proto3"

var (
	file_remaccessmgr_v1_remacessmgr_proto_rawDescOnce sync.Once
	file_remaccessmgr_v1_remacessmgr_proto_rawDescData []byte
)

func file_remaccessmgr_v1_remacessmgr_proto_rawDescGZIP() []byte {
	file_remaccessmgr_v1_remacessmgr_proto_rawDescOnce.Do(func() {
		file_remaccessmgr_v1_remacessmgr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_remaccessmgr_v1_remacessmgr_proto_rawDesc), len(file_remaccessmgr_v1_remacessmgr_proto_rawDesc)))
	})
	return file_remaccessmgr_v1_remacessmgr_proto_rawDescData
}

var file_remaccessmgr_v1_remacessmgr_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_remaccessmgr_v1_remacessmgr_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_remaccessmgr_v1_remacessmgr_proto_goTypes = []any{
	(ConfigStatus)(0),                          // 0: remaccessmgr.v1.ConfigStatus
	(*GetRemoteAccessConfigByGuidRequest)(nil), // 1: remaccessmgr.v1.GetRemoteAccessConfigByGuidRequest
	(*AgentRemoteAccessSpec)(nil),              // 2: remaccessmgr.v1.AgentRemoteAccessSpec
	(*ConfigError)(nil),                        // 3: remaccessmgr.v1.ConfigError
	(*GetResourceAccessConfigResponse)(nil),    // 4: remaccessmgr.v1.GetResourceAccessConfigResponse
	(*timestamppb.Timestamp)(nil),              // 5: google.protobuf.Timestamp
}
var file_remaccessmgr_v1_remacessmgr_proto_depIdxs = []int32{
	5, // 0: remaccessmgr.v1.GetResourceAccessConfigResponse.observed_at:type_name -> google.protobuf.Timestamp
	0, // 1: remaccessmgr.v1.GetResourceAccessConfigResponse.status:type_name -> remaccessmgr.v1.ConfigStatus
	2, // 2: remaccessmgr.v1.GetResourceAccessConfigResponse.spec:type_name -> remaccessmgr.v1.AgentRemoteAccessSpec
	3, // 3: remaccessmgr.v1.GetResourceAccessConfigResponse.error:type_name -> remaccessmgr.v1.ConfigError
	1, // 4: remaccessmgr.v1.RemaccessmgrService.GetRemoteAccessConfigByGuid:input_type -> remaccessmgr.v1.GetRemoteAccessConfigByGuidRequest
	4, // 5: remaccessmgr.v1.RemaccessmgrService.GetRemoteAccessConfigByGuid:output_type -> remaccessmgr.v1.GetResourceAccessConfigResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_remaccessmgr_v1_remacessmgr_proto_init() }
func file_remaccessmgr_v1_remacessmgr_proto_init() {
	if File_remaccessmgr_v1_remacessmgr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_remaccessmgr_v1_remacessmgr_proto_rawDesc), len(file_remaccessmgr_v1_remacessmgr_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_remaccessmgr_v1_remacessmgr_proto_goTypes,
		DependencyIndexes: file_remaccessmgr_v1_remacessmgr_proto_depIdxs,
		EnumInfos:         file_remaccessmgr_v1_remacessmgr_proto_enumTypes,
		MessageInfos:      file_remaccessmgr_v1_remacessmgr_proto_msgTypes,
	}.Build()
	File_remaccessmgr_v1_remacessmgr_proto = out.File
	file_remaccessmgr_v1_remacessmgr_proto_goTypes = nil
	file_remaccessmgr_v1_remacessmgr_proto_depIdxs = nil
}
