// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: remaccessmgr/v1/remacessmgr.proto

package remaccessmgrv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _remacessmgr_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on GetRemoteAccessConfigByGuidRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *GetRemoteAccessConfigByGuidRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRemoteAccessConfigByGuidRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// GetRemoteAccessConfigByGuidRequestMultiError, or nil if none found.
func (m *GetRemoteAccessConfigByGuidRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRemoteAccessConfigByGuidRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetUuid()) > 36 {
		err := GetRemoteAccessConfigByGuidRequestValidationError{
			field:  "Uuid",
			reason: "value length must be at most 36 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetUuid()); err != nil {
		err = GetRemoteAccessConfigByGuidRequestValidationError{
			field:  "Uuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetTenantID()) > 36 {
		err := GetRemoteAccessConfigByGuidRequestValidationError{
			field:  "TenantID",
			reason: "value length must be at most 36 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetTenantID()); err != nil {
		err = GetRemoteAccessConfigByGuidRequestValidationError{
			field:  "TenantID",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetRemoteAccessConfigByGuidRequestMultiError(errors)
	}

	return nil
}

func (m *GetRemoteAccessConfigByGuidRequest) _validateUuid(uuid string) error {
	if matched := _remacessmgr_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetRemoteAccessConfigByGuidRequestMultiError is an error wrapping multiple
// validation errors returned by
// GetRemoteAccessConfigByGuidRequest.ValidateAll() if the designated
// constraints aren't met.
type GetRemoteAccessConfigByGuidRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRemoteAccessConfigByGuidRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRemoteAccessConfigByGuidRequestMultiError) AllErrors() []error { return m }

// GetRemoteAccessConfigByGuidRequestValidationError is the validation error
// returned by GetRemoteAccessConfigByGuidRequest.Validate if the designated
// constraints aren't met.
type GetRemoteAccessConfigByGuidRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRemoteAccessConfigByGuidRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRemoteAccessConfigByGuidRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRemoteAccessConfigByGuidRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRemoteAccessConfigByGuidRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRemoteAccessConfigByGuidRequestValidationError) ErrorName() string {
	return "GetRemoteAccessConfigByGuidRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetRemoteAccessConfigByGuidRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRemoteAccessConfigByGuidRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRemoteAccessConfigByGuidRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRemoteAccessConfigByGuidRequestValidationError{}

// Validate checks the field values on AgentRemoteAccessSpec with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AgentRemoteAccessSpec) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AgentRemoteAccessSpec with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AgentRemoteAccessSpecMultiError, or nil if none found.
func (m *AgentRemoteAccessSpec) ValidateAll() error {
	return m.validate(true)
}

func (m *AgentRemoteAccessSpec) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RemoteAccessProxyEndpoint

	// no validation rules for SessionToken

	// no validation rules for ReverseBindPort

	// no validation rules for TargetHost

	// no validation rules for TargetPort

	// no validation rules for SshUser

	// no validation rules for ExpirationTimestamp

	// no validation rules for Uuid

	if len(errors) > 0 {
		return AgentRemoteAccessSpecMultiError(errors)
	}

	return nil
}

// AgentRemoteAccessSpecMultiError is an error wrapping multiple validation
// errors returned by AgentRemoteAccessSpec.ValidateAll() if the designated
// constraints aren't met.
type AgentRemoteAccessSpecMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AgentRemoteAccessSpecMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AgentRemoteAccessSpecMultiError) AllErrors() []error { return m }

// AgentRemoteAccessSpecValidationError is the validation error returned by
// AgentRemoteAccessSpec.Validate if the designated constraints aren't met.
type AgentRemoteAccessSpecValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AgentRemoteAccessSpecValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AgentRemoteAccessSpecValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AgentRemoteAccessSpecValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AgentRemoteAccessSpecValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AgentRemoteAccessSpecValidationError) ErrorName() string {
	return "AgentRemoteAccessSpecValidationError"
}

// Error satisfies the builtin error interface
func (e AgentRemoteAccessSpecValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAgentRemoteAccessSpec.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AgentRemoteAccessSpecValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AgentRemoteAccessSpecValidationError{}

// Validate checks the field values on ConfigError with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ConfigError) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConfigError with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ConfigErrorMultiError, or
// nil if none found.
func (m *ConfigError) ValidateAll() error {
	return m.validate(true)
}

func (m *ConfigError) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	if len(errors) > 0 {
		return ConfigErrorMultiError(errors)
	}

	return nil
}

// ConfigErrorMultiError is an error wrapping multiple validation errors
// returned by ConfigError.ValidateAll() if the designated constraints aren't met.
type ConfigErrorMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConfigErrorMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConfigErrorMultiError) AllErrors() []error { return m }

// ConfigErrorValidationError is the validation error returned by
// ConfigError.Validate if the designated constraints aren't met.
type ConfigErrorValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConfigErrorValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConfigErrorValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConfigErrorValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConfigErrorValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConfigErrorValidationError) ErrorName() string { return "ConfigErrorValidationError" }

// Error satisfies the builtin error interface
func (e ConfigErrorValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConfigError.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConfigErrorValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConfigErrorValidationError{}

// Validate checks the field values on GetResourceAccessConfigResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetResourceAccessConfigResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetResourceAccessConfigResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetResourceAccessConfigResponseMultiError, or nil if none found.
func (m *GetResourceAccessConfigResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetResourceAccessConfigResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Seq

	if all {
		switch v := interface{}(m.GetObservedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetResourceAccessConfigResponseValidationError{
					field:  "ObservedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetResourceAccessConfigResponseValidationError{
					field:  "ObservedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetObservedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetResourceAccessConfigResponseValidationError{
				field:  "ObservedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetSpec()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetResourceAccessConfigResponseValidationError{
					field:  "Spec",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetResourceAccessConfigResponseValidationError{
					field:  "Spec",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSpec()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetResourceAccessConfigResponseValidationError{
				field:  "Spec",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetError()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetResourceAccessConfigResponseValidationError{
					field:  "Error",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetResourceAccessConfigResponseValidationError{
					field:  "Error",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetError()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetResourceAccessConfigResponseValidationError{
				field:  "Error",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetResourceAccessConfigResponseMultiError(errors)
	}

	return nil
}

// GetResourceAccessConfigResponseMultiError is an error wrapping multiple
// validation errors returned by GetResourceAccessConfigResponse.ValidateAll()
// if the designated constraints aren't met.
type GetResourceAccessConfigResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetResourceAccessConfigResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetResourceAccessConfigResponseMultiError) AllErrors() []error { return m }

// GetResourceAccessConfigResponseValidationError is the validation error
// returned by GetResourceAccessConfigResponse.Validate if the designated
// constraints aren't met.
type GetResourceAccessConfigResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetResourceAccessConfigResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetResourceAccessConfigResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetResourceAccessConfigResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetResourceAccessConfigResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetResourceAccessConfigResponseValidationError) ErrorName() string {
	return "GetResourceAccessConfigResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetResourceAccessConfigResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetResourceAccessConfigResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetResourceAccessConfigResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetResourceAccessConfigResponseValidationError{}
