---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Post-Merge Networking

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - "networking/**"

permissions: {}

jobs:
  post-merge-pipeline:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: open-edge-platform/orch-ci/.github/workflows/post-merge.yml@main
    with:
      run_version_check: true
      run_dep_version_check: true
      run_build: true
      run_docker_build: true
      run_docker_push: true
      run_version_tag: true
      run_artifact: false
      prefix_tag_separator: "/"
      project_folder: "networking"
    secrets: inherit
